### ISSUE TITLE
Local file?

### ISSUE THREAD

**Issue by lurchpop** [IonicaBizau/scrape-it#102]
I've done a wget -r on a site I want to scrape locally. Is there a way to do it on local files? Tried with file:// protocol and didn't work :(

**Comment by IonicaBizau** [comment]
Use the [`scrapeHTML` method](https://github.com/IonicaBizau/scrape-it#scrapeitscrapehtml-opts).

```js
const fs = require("fs")
const scrapeIt = require("scrape-it")

const data = scrapeIt.scrapeHTML(fs.readFileSync("that-file.html", "utf-8"), {
  title: "h2#title" // your scrape it schema
})
```
