### ISSUE TITLE
Get URL after redirects

### ISSUE THREAD

**Issue by bfelbo** [IonicaBizau/scrape-it#104]
How would I get the URL that scrape-it ends on after it has encountered one or more redirects from the original URL I passed to it?

**Comment by bfelbo** [comment]
I've tried the following based on https://stackoverflow.com/questions/16687618/how-do-i-get-the-redirected-url-from-the-nodejs-request-module, but `response.headers.location` is undefined. 

```
const scrapeIt = require("scrape-it")
const useragent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36"

// Promise interface
scrapeIt({url: "http://fb.me/5dVLyJbX8", headers: { "User-agent": useragent }}, {
    title: "title"
  , desc: ".header h2"
  , avatar: {
        selector: ".header img"
      , attr: "src"
    }
}).then(({ data, response, body }) => {
    console.log(`Status Code: ${response.statusCode}`)
    console.log(data)
    console.log(response.headers.location)
    //console.log(response.request.uri.href) // throws error
}).catch((err) => console.log("CAUGHT", err))
```

**Comment by IonicaBizau** [comment]
Can you check if `response.responseUrl` is what you want?

We use [`follow-redirects`](https://github.com/olalonde/follow-redirects) to follow the redirects.

**Comment by bfelbo** [comment]
That also returns `undefined` when printed. The title is scraped fine from the [final website](https://www.straight.com/news/699761/david-suzuki-eat-less-meat-reduce-earths-heat) so `scrape-it` is working as intended. It's just getting the new URL that's the problem.

**Comment by IonicaBizau** [comment]
You're right! They added this property recently.
I've upgraded the `follow-redirects` version in `tinyreq` and it should work now.

You may need to delete `package-lock.json` locally and `npm i`. 😁  🚀

**Comment by IonicaBizau** [comment]
For reference: https://github.com/IonicaBizau/tinyreq/pull/36

**Comment by bfelbo** [comment]
That works. Amazing, thanks!
