### ISSUE TITLE
Add support to lt/gt functions

### ISSUE THREAD

**Issue by alexschwarz89** [IonicaBizau/scrape-it#105]
Scraping multiple values in a list it could be useful to implement the gt (greater than) and lt (lower than) class in addition to the already implemented eq (equals).

**Comment by alexschwarz89** [comment]
My first thoughts were new attributes on the same level as `listSelector`, possible names could be `offset` and `limit`.

So for example, a configuration for scraping the current NGINX [versions(https://nginx.org/en/download.html) could look like
````javascript
                listSelector: "#content table",
                data: {
                    version: {
                        limit: 2,
                        eq: 1,
                        selector: "td a"
                    }
                }
```
because anything above are the legacy versions, i don't want to scrape. Now imagine you dont wan't the first table, and there is no `class` or `id` to filter, you could define an `offset: 1`.

What do you think?

**Comment by IonicaBizau** [comment]
I think this should be part of the post-scraping logic.
