### ISSUE TITLE
Async-await

### ISSUE THREAD

**Issue by IonicaBizau** [IonicaBizau/scrape-it#107]
It doesn't seem to play well with async-await...

https://runkit.com/5af6881085a6d600128df514/5af68811cb36580012bde274?

**Comment by aflansburg** [comment]
Altering your code sample seems to work:

`const scrapeIt = require("scrape-it")

async function aFunc(){
    return await scrapeIt("https://nmotw.in", {tagLine: ".tagline"})
}

aFunc().then(res=>console.log(res))`

**Comment by IonicaBizau** [comment]
This should work now.
