### ISSUE TITLE
Simulate click

### ISSUE THREAD

**Issue by Stas-Buzunko** [IonicaBizau/scrape-it#108]
Thanks for a great lib!

I've had a look at https://github.com/IonicaBizau/scrape-it/issues/7 but still not sure whether it's possible to simulate a click.

A simple case is where you have to click on a button/link to see a hidden Phone number

Is it possible with your library? If so, can you show an example

**Comment by IonicaBizau** [comment]
If you want to simulate user behavior, use a headless browser (such as Nightmare, Google Chorome, PhantomJS) and there you simulate clicks and wait, and then pass the HTML code to `scrapeIt.scrapeHTML`.

**Comment by Stas-Buzunko** [comment]
thanks
