### ISSUE TITLE
How can I get all the values of an attribute in a tag?

### ISSUE THREAD

**Issue by wxy1995** [IonicaBizau/scrape-it#135]
I want to get data with the following structure:
```
{
    'imgUrls': [
        'https://aa.png',
        'https://bb.png',
        'https://cc.png',
     ]
}
```

Is there any solution?

**Comment by wayneconnolly** [comment]
The below will get you close and then you will have to use standard array manipulation to rebuild an array to suit your structure.

imgs: {
		        listItem: "div.photoContainer"
		      , name: "count"
		      , data: {
		            url: {
		                selector: "img"
		              , attr: "src"
		            }
		        }
		    }


This returns

  imgs: [
    { url: 'https://pbs.twimg.com/media/EDvU7wcWkAM9IyH.jpg' },
    { url: 'https://pbs.twimg.com/media/EDvU8BrW4AAYeit.jpg' },
    { url: 'https://pbs.twimg.com/media/EDvU8QFXYAAtoIO.jpg' }
  ],

**Comment by IonicaBizau** [comment]
Yes, @wayneconnolly's answer should work. Please ask questions on Stackoverflow.
