### ISSUE TITLE
getting unexpected characters instead outerHTML string 

### ISSUE THREAD

**Issue by dagi377** [IonicaBizau/scrape-it#141]
Thank you for very helpful library. 

I am scraping a multilingual content, and one of the is language is Russian. I am getting this very unexpected characters(I think unicode) instead of normal strings. This is problematic for my database searches. 

I think some where in the library if  function config    ` how:"html"`   is used , then the strings are changed to hexadecimal char like representation.When I embed it in the browser it gives me normal html out put but storing these characters in the database is problematic. When I omit this option the the innerText is returned successfully. But I want all the html part of the scrapped content. 

can you help? 

I think it is related to cherio, please look here https://github.com/cheeriojs/cheerio/issues/565

thanks 

Here is more info on  sample configuration 

`
{
   "selectors":{
      "getURLs":{
         "articles":{
            "listItem":".news-inline-item",
            "data":{
               "url":{
                  "selector":"a",
                  "attr":"href"
               }
            }
         }
      },
      "getPostContent":{
         "title":".article-column h1",
         "content":{
            "selector":".article-text",
            "how":"html"
         },
         "images":{
            "listItem":".article-text",
            "data":{
               "img":{
                  "selector":"img",
                  "attr":"src"
               }
            }
         }
      }
   }
}
`

### 
Here is the url [https://www.unian.ua/economics/agro/10708731-ukrajina-skorotila-eksport-cukru-mayzhe-na-tretinu.html](url)

**Comment by dagi377** [comment]
Thanks 
I resolved it using Cherio, I think it's good if we have such config in this lib


`   const ch = cheerio.load(`<div>${content}</div>`, { decodeEntities: false });
    return ch('div').html();`

**Comment by minasvisual** [comment]
Has a way to set this config on scrapeit ops?
