### ISSUE TITLE
Hosted API

### ISSUE THREAD

**Issue by chrisvxd** [IonicaBizau/scrape-it#142]
Hey @IonicaBizau 👋 Thanks for the awesome library.

I'm looking to convert open source libs into SaaS APIs as part of my work with [saasify.sh](https://saasify.sh) and thought scrape-it would be a great fit.

Here's a working demo of what I was thinking, generated from [this source](https://github.com/saasify-sh/scrape-it/):

```bash
curl -X POST \
  'https://api.saasify.sh/1/call/dev/scrape-it@ad97b8f8/index' \
  -H 'content-type: application/json' \
  -d '{
  "url": "https://ionicabizau.net",
  "opts": {
    "title": ".header h1",
    "desc": ".header h2",
    "avatar": {
      "selector": ".header img",
      "attr": "src"
    }
  }
}'
```

We'd like to offer a rate-limited API and reserve most of the profits for you. As an example, we've also worked on converting sindresorhus' [imagemin](http://imagemin.saasify.sh/) and minimaxir's [stylecloud](http://wordcloud.saasify.sh/) to APIs.

Looking forward to hearing your thoughts! Would also be happy to jump on a quick call to discuss.

**Comment by IonicaBizau** [comment]
That is amazing! ❤️

I do advise in that you will have accounts or some kind of user authentication so that in case they abuse your server (by making requests to _weird_ urls) you will be able to stop these requests.

Anyways, it's a wonderful idea! ✨

**Comment by IonicaBizau** [comment]
> Would also be happy to jump on a quick call to discuss.

I am very busy at the moment, but I think email works better: contact@ionicabizau.net.

**Comment by chrisvxd** [comment]
@IonicaBizau so glad to hear you like it!

We automatically add public rate limits to each of our APIs, so that shouldn't be a concern. To remove the limit, people need to add billing information.

I'll keep the discussion in this thread, if that's alright? We also have [an open slack](https://join.slack.com/t/saasify/shared_invite/enQtODAxODA5MzU0NjczLTczOGU3NzNkYTJlMWIwZDkyNjJkOTk3MGEwZThlOWQyNTQxODZjZTExNjAzODJlZDQ3MWM5NWQwMGRiMDcyZTY) if you want to join.

If you're keen, the next steps I'd take are:
1. Polish the [landing page](https://dev_scrape-it_ad97b8f8.saasify.sh) by tweaking the [`saasify.json`](https://github.com/saasify-sh/scrape-it/blob/master/saasify.json)
2. Add some documentation
3. Publish it to the domain `scrape-it.saasify.sh`
4. Set up payouts to you - we can discuss this again once everything else is put together, but let me know if you have any questions about that.

Ideally I'd also love to add a button to your README to help funnel some of your users towards the API. This should appeal to your visitors that aren't using node, or users who don't want to bloat their payload. Something like:

<a href="https://dev_scrape-it_ad97b8f8.saasify.sh" target="_blank">
  <img
    src="https://badges.saasify.sh?text=View%20Hosted%20API"
    height="40"
    alt="View Hosted API"
  />
</a>

**Comment by IonicaBizau** [comment]
That's wonderful! Just joined Slack.

Let me know if you have any questions and I will be happy to help.

Best!

**Comment by chrisvxd** [comment]
I've just published the latest version to https://scrape-it.saasify.sh 🙌

See the src here: https://github.com/saasify-sh/scrape-it

Let me know what you think!

**Comment by IonicaBizau** [comment]
That's lovely! I like the HN example.
