### ISSUE TITLE
Cannot find name Cheerio / CheerioSelector / CheerioStatic

### ISSUE THREAD

**Issue by clapointe** [IonicaBizau/scrape-it#157]
I have scrape-it as a dependency of another package in my project (nest-crawler). I encountered these 3 errors in my project when trying to start nestjs: 
Cannot find name Cheerio / CheerioSelector / CheerioStatic

I searched around for a while before finding how to fix it for my project: adding "@types/cheerio": "0.22.13" in the devDependencies (note: not "^0.22.13")

Since that's just a quick fix, I figured I'd open an issue in case anyone else is having this problem.

**Comment by chauchakching** [comment]
@clapointe 
In case you're still having issue, give [scrape-brrr](https://github.com/chauchakching/scrape-brrr) a try!
It's a similar scraper created to solve my own niche, and you may find it useful
