### ISSUE TITLE
Add support for conditional selector

### ISSUE THREAD

**Issue by 41y08h** [IonicaBizau/scrape-it#158]
Hey Ionica thanks for this awesome library, I've an idea about a function.
I just discovered a situation described below and I think it would be very helpful if you can add some sort of function for conditional selecting, as css selectors don't have if else blocks.

The data looks something like this - 

```
<tbody>
                                
<tr>
<th>Net Sales</th>
<td><span class="Number" value="3776.36">3,776.36</span></td>
<td><span class="Number" value="4064.34">4,064.34</span>
<td><span class="Number" value="3776.36">3,776.36</span></td>
<td><span class="Number" value="3776.36">3,776.36</span></td>
</tr>

<tr>
<th>Operating Income</th>
<td><span class="Number" value="3776.36">3,776.36</span></td>
<td><span class="Number" value="4064.34">4,064.34</span>
<td><span class="Number" value="3776.36">3,776.36</span></td>
<td><span class="Number" value="3776.36">3,776.36</span></td>
</tr>
     
</tbody>
```

I want to select some info from a `tr td` conditionally based on text content of `th` .

**Comment by IonicaBizau** [comment]
This should be added in the post-scraping logic.
