### ISSUE TITLE
Move scrapeHTML into its own package

### ISSUE THREAD

**Issue by malte-v** [IonicaBizau/scrape-it#161]
I'd like to use your package from a React Native app, where the Node.js core modules are not available. scrape-it indirectly depends on tinyreq, which in turn uses Node's `url` module. I'm only using `scrapeHTML`, so all the networking stuff is not required. Could you move `scrapeHTML` into its own package, say "scrape-it-core", so people can use the offline functionalily independently? Thanks!

**Comment by IonicaBizau** [comment]
I was thinking of this too. Perhaps will wokr on this next days. Thanks for the idea! :sparkles:
