### ISSUE TITLE
Single page applications

### ISSUE THREAD

**Issue by DarrylD** [IonicaBizau/scrape-it#17]
Is it anything special I need to so to wait for dynamic elements to be ready? Want to use it for a site that uses angular and everything is pulled in via ajax.

**Comment by IonicaBizau** [comment]
Currently that's not supported, but I'll soon have a solution for it.

**Comment by IonicaBizau** [comment]
@DarrylD The current solution is to use a headless browser (e.g. PhantomJS or Electron) and pass the HTML to the [`scrapeHTML` method](https://github.com/IonicaBizau/scrape-it#scrapeitscrapehtml-opts).

**Comment by DarrylD** [comment]
I'm using phantom now and kinda wanted to have something more lightweight like what you have.

**Comment by guillaumegaluz** [comment]
hey @IonicaBizau - wondering if you were still planning on providing an API for async loading pages? thanks!

**Comment by IonicaBizau** [comment]
@guillaumegaluz When you deal with such pages, I found that the best idea is to pick a headless browser that you're comfortable with and pass the HTML to the `scrapeHTML` method.
