### ISSUE TITLE
Scrape Behind Login

### ISSUE THREAD

**Issue by mistertest** [IonicaBizau/scrape-it#176]
Hello.
So I'm using Scrape it CLI for my project because, it's not working for me from browser and cors limitations.

So my question, can I use Scrap it cli behind a login of Web site ?
And how, please. 

Thank you, for your help , I will mention this great tool "scrape it" and You in my md soon.

**Comment by IonicaBizau** [comment]
You should be able to pass the auth cookies. But I don't think that's possible with scrape-it-cli currently.
