### ISSUE TITLE
How would you handle authentication ?

### ISSUE THREAD

**Issue by gpapin** [IonicaBizau/scrape-it#25]
Hi,
I need to scrape a webpage on a site that is member only. How would I use a coockie or authenticate myself against this website (is it even possible using this lib ? )

**Comment by IonicaBizau** [comment]
@gpapin Yes, you can send the `Cookie` header in in the options:

```js
// Promise interface
scrapeIt({
    url: "http://ionicabizau.net"
  , headers: { Cookie: "foo=bar; baz=foo" }
}, {...}).then(...);
```

**Comment by IonicaBizau** [comment]
For reference, check out the `tinyreq` docs: https://github.com/IonicaBizau/tinyreq#tinyreqoptions-callback

**Comment by gpapin** [comment]
Thanks for your prompt answer I'll check that right away ! :)

**Comment by curtisturner** [comment]
Is there cookie jar support or will cookies have to be manually parsed from response and loaded into req headers?

**Comment by IonicaBizau** [comment]
@curtisturner Not really, but you can use modules to stringify/serialize cookie objects into strings that can be passed in the `Cookie` header.
