### ISSUE TITLE
Missing timeout option

### ISSUE THREAD

**Issue by Jordi-m** [IonicaBizau/scrape-it#28]
Hi,

I've tried to use this library to scrape about 40 website asynchronously. I do this by using the Promise object returned by ScrapeIt, and then doing something like this

`Promise.all(promises).then( function(result){`

The problem here is that one of the websites I scrape can be down/slow at unspecified times (I have no control over it). The problem with the library is that ScrapeIt never seems to time out (tried it for a few minutes, but it won't return and run the Promise.all ... code.

Any suggestion on how I can make it timeout (while still using the library promises)? Did I miss any option?

**Comment by IonicaBizau** [comment]
@Jordi-m What if it returned an error? It's probably using the default timeout from the Node.js request functionality.

**Comment by Jordi-m** [comment]
I did add the catch, but in the last three days all the 40 websites are up and running; I'm unable to get this situation reproduces myself (even added a long loading URL). If it becomes an issue again, I'll get back to this Github issue. Thank you for the suggestion so far.

**Comment by IonicaBizau** [comment]
@Jordi-m I will keep an eye on it too. I'm also scraping lots of pages and didn't have this problem yet...

**Comment by Jordi-m** [comment]
@IonicaBizau It's been a while, but today I've spotted the problem mentioned in this issue again. I've immediately tried to find out which website it is.

It turns out that this specific website is causing an infinite(?) HTTP redirect. When visiting this page in browser, the developer console shows HTTP 508: Loop detected. I suspect the library will just wait 'forever' for the redirect to stop?

**Comment by IonicaBizau** [comment]
@Jordi-m Hmm, good point. Reported here: https://github.com/olalonde/follow-redirects/issues/41

**Comment by Jordi-m** [comment]
I just discovered my mass-scrape script fails again on some URL's I cannot retrieve any content from. It seems like they also somehow get passed the timout option.

For example, take this URL (note, it's depending on time if it works on not, currently it doesn't): http://www.cavenergie.nl/feed/

* Before reporting this I've updated the libraries via NPM.

**Comment by IonicaBizau** [comment]
This should be fixed now.
