### ISSUE TITLE
301 Redirect Handling

### ISSUE THREAD

**Issue by ErikAugust** [IonicaBizau/scrape-it#29]
Would be a nice feature to implement. Could work on, and PR if necessary.

**Comment by IonicaBizau** [comment]
@ErikAugust This should be fixed in [`tinyreq`](https://github.com/IonicaBizau/tinyreq). That would be cool! 👍

**Comment by IonicaBizau** [comment]
This should be fixed now: https://github.com/IonicaBizau/tinyreq/pull/15
