### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by gabrielseco** [IonicaBizau/scrape-it#33]
I used the scrape-it module before and it didn't give me any errors.

I thought that it was in my repo the error, but I got it downloading this repo.

I npm install the dependencies and I tried to run the example index.js with node index.js

The error is the next

```
Gabriel at iMac-de-Gabriel in ~/scrape-it/example on master*
$ node index
{ Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }
```

 I have node 6.5.0 and npm 3.10.3

**Comment by hansbeld** [comment]
I have the exact same problem. node v6.6.0 and npm 3.10.3

**Comment by IonicaBizau** [comment]
Sorry guys. It happened due to a mistake in the previous version of `ul` (the tests were not covering that use-case also).

Fixed in the latest patch release of [`ul`](https://github.com/IonicaBizau/node-ul). `npm update` should be enough to fix the things. :rocket:
