### ISSUE TITLE
Can I target a Dom or a String instead of a URL?

### ISSUE THREAD

**Issue by sscarduzio** [IonicaBizau/scrape-it#34]
I'm forced to use casperjs for logging in and render the JS of the site I'm scraping. That means I already have the Dom. How can I pass it to scrape-it directly?

**Comment by IonicaBizau** [comment]
@sscarduzio Of course, if you have some HTML  as a string or cheerio object, you can pass it to the [`scrapeHTML`](https://github.com/IonicaBizau/scrape-it#scrapeitscrapehtml-opts) method.

**Comment by sscarduzio** [comment]
Great news, thanks I will try :)

**Comment by gencaysahinn** [comment]
@sscarduzio  Did you succeed it?
