### ISSUE TITLE
Set user agent

### ISSUE THREAD

**Issue by michaelmior** [IonicaBizau/scrape-it#36]
I came across a site I'm trying to scrape which does not return results unless the User-Agent header is set. It's probably good practice anyway to set it to something like "scrape-it X.Y.Z" to self-identify. Alternatively, my problem would be solved if it were possible to pass options through to the underlying request which I could imagine being useful for other purposes too.

**Comment by IonicaBizau** [comment]
@michaelmior Use the `headers` object:

```js
// Promise interface
scrapeIt({
    url: "http://ionicabizau.net"
  , headers: { "User-agent": "scrape-it X.Y.Z" }
}, {...}).then(...);
```

By passing an object instead of a string, you're passing the options. Hope it helps!

**Comment by michaelmior** [comment]
Sorry, I must have missed this in the documentation. Although it should have been painfully obvious after I looked at the code. Thanks :)

**Comment by IonicaBizau** [comment]
@michaelmior No worries, feel free to ask when you're in need. 😁 Have fun with this library!
