### ISSUE TITLE
Promises!

### ISSUE THREAD

**Issue by benjamingr** [IonicaBizau/scrape-it#4]
K thanks.

**Comment by IonicaBizau** [comment]
Hey @benjamingr! :grin: 

True, I was waiting for someone to open this subject. This is a bit more general thing, across my modules (they are using callbacks) and I have this on my list. Maybe this would be a good start.

**Comment by IonicaBizau** [comment]
@benjamingr This is now available in **`2.1.0`**. :tada: I used [`assured`](https://github.com/IonicaBizau/assured) to keep the callback interface too.

**Comment by curtisturner** [comment]
Hi, is there away to get access to res and body via promise interface? Or is it only avail via using callback interface?

**Comment by IonicaBizau** [comment]
@curtisturner I'm not sure—by calling `resolve`, can we send more than one parameter? If so, that should be already there. Otherwise, I'm not really sure how we should handle that. How would you like to access these values? 💭

**Comment by benjamingr** [comment]
No, you can't - you can use an object or array and use destructuring or `.spread`
