### ISSUE TITLE
Scrape in a nested ul li list ?

### ISSUE THREAD

**Issue by yopbeast** [IonicaBizau/scrape-it#41]
I am sorry but i am in trouble, hope somebody can help me, i have this page i want to scrape:

```html
<ul>
<li><a>1</a></li>
<li><a>2</a></li>
<li><a>3</a></li>
<li><a>4</a></li>
</ul>

<ul>
<li><a>1</a></li>
<li><a>2</a></li>
<li><a>3</a></li>
<li><a>4</a></li>
</ul>
```

I need the ul li a content of the second <ul> element, not the first one , so i did:

```{
selector: 'ul',
eq: 2
}```


but it doesn't seems to work, can you please help me ?

thanks

**Comment by IonicaBizau** [comment]
@yopbeast Can you please create a file containing the script and put it here?

**Comment by yopbeast** [comment]
sorry was my mistake everythings works
