### ISSUE TITLE
Scrape bunch of urls Array?

### ISSUE THREAD

**Issue by yopbeast** [IonicaBizau/scrape-it#42]
Hi, i have a bunch of urls in array that i want to scrape, can you tell me if this is the correct way to achieve it:

```javascript

for (i in urls) {
scrapeIt(i, {
selector: '#gradients',
how: 'html'
}).then((data) => {
console.log('DONE with url', ${i}, data);
});
}
```

i think it works but it takes too much time, i don't know why and how to debug so i am asking you, thanks for patience!

**Comment by IonicaBizau** [comment]
Use `Promise.all`:

```js
Promise.all(urls.map(c => scrapeIt(c, {
   selector: '#gradients',
   how: 'html'
})).then(data => {
   console.log(data);
   // [{...}, {...}, ...]
});
```

But this won't be faster, just the code looks better.

Note that I didn't test it.
