### ISSUE TITLE
Is there support for scraping single elements in table?

### ISSUE THREAD

**Issue by 19r3ka** [IonicaBizau/scrape-it#43]
Hi,

I have this simple code that fails everytime.

```
var player = {
    url: "https://fr.wikipedia.org/wiki/Kossi_Agassa",
    data: {
        club: {
            selector: "#mw-content-text > table.wikitable.alternance2.centre > tbody > tr:nth-child(3) > td:nth-child(2) > span > b > a"
        }
    }
};

scrape(player.url, player.data)
    .then(console.log)
    .catch(console.error);

```
The output is always { club: '' } when it really should be { club: "FC Metz" }

Selecting table rows as listItem data seems to work but never selecting single elements from a table. I even tried with "#mw-content-text > table.infobox_v2 > tbody > tr:nth-child(4) > td > a". However, selecting single element outside of tables also works like a charm.

What am I doing wrong?

**Comment by IonicaBizau** [comment]
Can you paste the HTML as well, please?

Maybe create a gist with the complete code.

**Comment by IonicaBizau** [comment]
Ah, sorry, this is already the complete code. 😂 Checking.

**Comment by 19r3ka** [comment]
Complete code minus `var scrape = require("scrape-it")`  :)

I really love this module for its simplicity. Pairing it with "request" does wonders. I really don't want to move away from it.

**Comment by IonicaBizau** [comment]
That looks like a cheerio issue, but I think in the `scrape-it` spirit, it would be better to do something like this:

```js
var scrape = require(".");
var player = {
    url: "https://fr.wikipedia.org/wiki/Kossi_Agassa",
    data: {
        club: {
            selector: "#mw-content-text > table.wikitable.alternance2.centre tr",
            eq: 3,
            data: {
                _: {
                    selector: "td",
                    eq: 1
                }
            }
        }
    }
};

scrape(player.url, player.data)
    .then(console.log)
    .catch(console.error);
```

This outputs:

```js
{ club: { _: 'FC Metz' } }
```

**Comment by 19r3ka** [comment]
Thanks,

Your example truly clarifies things. **First, `eq` behaves more like a list (array) index than a true `nth:child`**. `eq: 2` is equivalent to `nth-child(3)`. I think you should add this nuance to the documentation on GitHub and NPM.

_Suggestion_: **You should stick to "nth-child" to comply with "html selectors" as much as possible**, thus making the module easier to pick up and even more "human".

Breaking the "options object" down into nested objects at every "eq / nth-child" makes the code less human-readable and forces to reformat the output. In my case, from "{ club: { _: 'FC Metz' } }" to {club: 'FC Metz'}.

That said, I am still sticking to this library. I really like it and look forward to seeing it grow in simplicity. Thanks again.

**Comment by IonicaBizau** [comment]
Great! ✨ 

I like `eq` because programmers start counting from `0`. 😁 Documentation improvements are always welcome! Just submit a PR! See this, btw: https://hacktoberfest.digitalocean.com

I agree. Maybe a solution would have to interpret a field like `_` as root, so, the library will do that for you.
