### ISSUE TITLE
Selecting a text node

### ISSUE THREAD

**Issue by vroudge** [IonicaBizau/scrape-it#45]
Hi guys,

Quick question:
Is it possible here to target the text content of the second node? I'm having a great deal of trouble to get it. 

Ideas?

```
<div id='foo'>
  <a>baz</a>
  "someText"
  <p>bar</p>
</div>
```

I expect to get "someText".

**Comment by IonicaBizau** [comment]
Currently not... :sob: Contributions are welcome in this direction. Related issue in Cheerio: https://github.com/cheeriojs/cheerio/issues/146

This is how we handle the `eq` option: https://github.com/IonicaBizau/scrape-it/blob/810560e4729b6cc6a7414fa1871ff38bc6e9c143/lib/index.js#L151-L153

It should be possible to add an option to select text nodes like that.

When I had this situation, I simply did:

```js
selector: "#foo",
how: "html",
convert (html) {
   return (html.match(/a\>(.*\)<p/g) || [])[1];
}
```

**Comment by vroudge** [comment]
That's exactly what I did!

I'll look it up.

**Comment by ifyour** [comment]
```js
// before
selector: "#foo",
how: "html",
convert (html) {
   return (html.match(/a\>(.*\)<p/g) || [])[1];
}
```

It would be better if the second argument returned `$`

```js
// after
selector: "#foo",
how: "html",
convert (html, $) {
   return $(html).text()
}
```
