### ISSUE TITLE
Attributes option does not work with 'data' attributes

### ISSUE THREAD

**Issue by alwayssonnyinco** [IonicaBizau/scrape-it#50]
Is there a way to pull data attributes such as `data-url`?

I've tried the following (example):

```
{
     title: ".header h1"
   , desc: ".header h2"
   , avatar: {
         selector: ".header img"
       , attr: "data-url"
     }
}
```

It appears that cheerio has a separate method for handling data attributes:
`$elm.data('url')`

If this is needed, I can create a PR.

**Comment by IonicaBizau** [comment]
I don't have to test that right now, but I find this more like a Cheerio issue. Can you give me a reference why the `attr("data-...")` is not working?

If so, contributions are welcome! :+1: 

Thanks!

**Comment by alwayssonnyinco** [comment]
Ah it looks like it was a typo in my code. My bad. Closing.

**Comment by IonicaBizau** [comment]
@alwayssonnyinco Ah, cool! :sweat_smile: Enjoy using it!
