### ISSUE TITLE
feature: cli

### ISSUE THREAD

**Issue by cztomsik** [IonicaBizau/scrape-it#51]
Is there any interest in adding CLI for this project?
BTW: I'd be happy to help.

What I'd love to use:

    scrape-it <url> <definition>

Also, piping would be great

    curl ... | scrape-it - <definition>

By `definition` I mean `*.js` file with

    module.exports = {
      articles: {
        listItem: ...
      }
    };

**Comment by IonicaBizau** [comment]
That would be great! :sparkles: 
For the cli module I'd recommend using [`tilda`](https://github.com/IonicaBizau/tilda).

Also, I would say to create a different project for the cli tool (e.g. `scrape-it-cli`).

Let me know if you have any questions! :smile:

**Comment by cztomsik** [comment]
I thought about [docopt](https://github.com/stuartcarnie/docopt.coffee)...
it's based on [this original project](http://docopt.org/)

The idea is that it takes usage string as DSL of your CLI. So all you have to write is this:

```
docopt(`
Usage:
  scrape-it <url> [--some-option]
  scrape-it -
  scrape-it -h | --help | --version

Options:
  --config=FILE  Config file [default: ./scrape-it.conf.js]
`)
```

And all of sudden you get something like this:

```
{
  url: 'http://...',
  config: './cfg.js',
  some-option: true
}
```

If you're okay with that I'd be happy to do it (and yeah it can be in its own repo)

**Comment by IonicaBizau** [comment]
@cztomsik Sure, feel free to use whatever you're comfortable with and share a link once it's on GitHub. :rocket: 

I'll be happy to add a link to it. :grin:

**Comment by cztomsik** [comment]
ok :)

**Comment by cztomsik** [comment]
Here's the [very first version](https://github.com/cztomsik/scrape-it-cli), it's not even published to npm yet, what do you think? Any ideas?

I was thinking about some default config or maybe an `init` command so people could start quickly?

Something like
```
npm i -g scrape-it-cli
scrape-it init
scrape-it http://github.com
```

and instantly get:
```
{ title: 'How people build software · GitHub' }
```

**Comment by IonicaBizau** [comment]
@cztomsik Cool! :+1:

**Comment by IonicaBizau** [comment]
@cztomsik Hey! Did you do any progress on this? Maybe we can work together for a stable release of `scrape-it-cli`.

**Comment by cztomsik** [comment]
Hey, not exactly, [basic version](https://github.com/cztomsik/scrape-it-cli) worked fine but I've actually found myself in need of something much more powerful (dozens of concurrent crawls backed in one big database) which I am working on and hopefully will open-source soon - I think you might like it and OFC we could join forces then :)

Anyway if you have ideas about scrape-it-cli I can certainly help you a little (or brainstorm) or even transfer the repo to you
