### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by barriojules** [IonicaBizau/scrape-it#53]
Hi, I couldn't find in the documentation if there is any option to collect data from various elements that matches one particular selector.

IE (collects all links from one particular site)
```
url: {
        selector: 'a',
        attr: "href"
    }
```

Is there an option like that ?

**Comment by IonicaBizau** [comment]
Use `how`––I wouldn't be against adding `attr` too!

```sh
url: {
        selector: 'a',
        how: "href"
}
```

**Comment by IonicaBizau** [comment]
And there's a similar example here: https://github.com/IonicaBizau/scrape-it/blob/810560e4729b6cc6a7414fa1871ff38bc6e9c143/example/index.js#L47-L57

**Comment by barriojules** [comment]
Thank you.

**Comment by IonicaBizau** [comment]
Actually `attr` is already supported. See the link above.
