### ISSUE TITLE
Maximum number in a list

### ISSUE THREAD

**Issue by niallel** [IonicaBizau/scrape-it#54]
Hi,

When I run the code below, it works for a certain number of items, then it outputs
"... 472 more items ] }"

Is there a configuration to limit the output that can be changed?

thanks,

`const scrapeIt = require("scrape-it");

scrapeIt("https://avia.nl/tankstations/", {
	stations: {
		listItem: ".search-result-inner-left",
		data: {
			name: {
				selector: "h3"
			},
			address1: {
				selector: ".first"
			},
			address2: {
				selector: ".first ~ span"
			}
		}
	}
}).then(page => {
    console.log(page);
});`

**Comment by IonicaBizau** [comment]
It's not related to `scrape-it`. It's either a Node.js cli feature or it's from your Terminal emulator. I'm not sure which of them.

**Comment by niallel** [comment]
Thanks for the quick reply.

You are right, when I iterate over each item it all outputs fine.

Thanks again,

**Comment by IonicaBizau** [comment]
I'm pretty sure it's from the terminal.

Try running it using:

```sh
node index.js > output.js
```

And then check out the `output.js`.

If I'm not wrong, I guess you're using the macOS Terminal app.

**Comment by niallel** [comment]
I did that straight away and got the same result. So i think it must be node
