### ISSUE TITLE
Question about parentNode

### ISSUE THREAD

**Issue by hjc1983** [IonicaBizau/scrape-it#55]
wondering if I use 'listItem', would I be able to traversing up the DOM tree to display info about the parentNode?

**Comment by IonicaBizau** [comment]
This is not currently possible but it's easy to be implemented. Just passing the `$elm` value in the `convert` function should be good enough I guess.

https://github.com/IonicaBizau/scrape-it/blob/810560e4729b6cc6a7414fa1871ff38bc6e9c143/lib/index.js#L166-L168
