### ISSUE TITLE
[Question] Getting attribute from listItem

### ISSUE THREAD

**Issue by Cliff122** [IonicaBizau/scrape-it#58]
I want to scrape a table with a bunch of cells, some of which have links in them. By using the options below I can get an array containing the text of the links.
```
{
  links: {
    listItem: "table tr td a"
  }
}		
```

However I need to get the href-attribute the links. How would I go about doing that?

**Comment by IonicaBizau** [comment]
See this example:

https://github.com/IonicaBizau/scrape-it/blob/master/example/index.js#L47-L57

```js
{
    links: {
        listItem: "table tr td"
      , data: {
            title: "a"
          , url: {
                selector: "a"
              , attr: "href"
            }
        }
    }
}
```

This should give you an array of objects containing the `url` field.

**Comment by Cliff122** [comment]
Yes, I tried that. However since not all cells include a link this method results in a bunch of empty objects in the array. Of course I can just filter those out, no problem there. I was just wondering if there was a built in method to avoid them in the first place.

**Comment by IonicaBizau** [comment]
Ah, I see!

Can you try this:

```js
{
    links: {
        listItem: "table tr td a"
      , data: {
            url: {
                // By not passing a selector, I assume it will use the current item
                attr: "href"
            }
        }
    }
}
```

**Comment by Cliff122** [comment]
That works! 😀 
Very clever solution, but it does make sense when you think about it. Thanks for the help! 👍

**Comment by IonicaBizau** [comment]
Phew! 😁 Cool! You're welcome!
