### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by gnimmelf** [IonicaBizau/scrape-it#70]
Hi,

I see this issue has been up before, but I got it now, always on consequent requests when scraping into scraped urls.

Error:
```
{ Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }
```

Gist of full code and package.lock-file: https://gist.github.com/gnimmelf/dd6bd5c8f518eb967ca93cec588a0b12

Any ideas?

Thank you!

**Comment by IonicaBizau** [comment]
`ECONNREFUSED 127.0.0.1:443`—this seems like `localhost` with `https`. I guess the error is coming from another side?

The code looks good.

**Comment by gnimmelf** [comment]
Hi,

Yes, the target is `https`, but the error looks like it is comming from my side, so that confuses me. 

Do you mean that the `ECONNREFUSED 127.0.0.1:443` *is* the target server response, from something behind a proxy of some sort on the remote side? -E.g a NodeJs-app behind Nginx. 

Does the scraper maintain any response-cookies etc across requests?

**Comment by IonicaBizau** [comment]
I assume it's something wrong between your machine and the server. The error is not coming from the remote server, but locally (e.g. if you try to request `https://localhost` or something similar I guess you'd get that error).

> Does the scraper maintain any response-cookies etc across requests?

No. You can send the cookies by setting the `Cookie` header.

**Comment by gnimmelf** [comment]
Hmm.

I just tried running the scraper on a Ubuntu server Digital Ocean server I have, but exactly the same result. So I guess the error is a real bummer in my script, which of course is really hard to see =)

Thanks for the feedback.
