### ISSUE TITLE
Doesn't work with gzip results

### ISSUE THREAD

**Issue by jadell** [IonicaBizau/scrape-it#72]
Not sure if this bug belongs in scrape-it, cheerio-req, or tinyreq.

A page I'm scraping is returning a result with 'content-encoding: gzip', and scrape-it isn't returning any results.

I traced functions calls and callbacks into the tinyrequest library, and it looks like it is passing the raw, gzipped body into cheerio.load()

I'm not sure the best way to handle this, my node-fu is not very strong. I tried overriding cheerio-req.request with a function that would unzip the body if the content-encoding is gzip, but I can't seem to get it working.

Any help would be appreciated.

**Comment by IonicaBizau** [comment]
@jadell Thanks for this! 

I and @coltaemanuela are on it here: https://github.com/IonicaBizau/tinyreq/pull/29

**Comment by jadell** [comment]
Awesome, thanks! I did eventually get a workaround by overriding the cheerio-req `request` function, using the `request` and `zlib` libraries. But it's good that this is being baked into the underlying `tinyreq` library.
