### ISSUE TITLE
List of links

### ISSUE THREAD

**Issue by divanvb** [IonicaBizau/scrape-it#78]
Hi

Can you possibly help me please, I'm trying to scrape a list of links not wrapped in a ul or li. There is an attr & name I want to store in one object and then the objects in a single array.

```
<div class="Content">

<a href="/ActionController/LeagueList?VenueId=6">Benoni</a>
<br>
<a href="/ActionController/LeagueList?VenueId=38">Bloemfontein</a>
<br>
...
```

I want to store the information like so: 

```
[{name: 'Benoni', url: 'https://...'}, ...]
```

I'm currently begin forced to make 2 calls to grab the name & url separately, any advice would be great thanks.

**Comment by divanvb** [comment]
Nevermind, figured it!

**Comment by RWOverdijk** [comment]
@divanvb Mind sharing your solution?
