### ISSUE TITLE
HELP :)

### ISSUE THREAD

**Issue by GlauberF** [IonicaBizau/scrape-it#82]
Hello, how can I use proxy.

I have a url with several ip and each call "scrapeIt (url, opts, cb)", I need to include an ip from my proxy list.

**Comment by ComFreek** [comment]
> I have a url with several ip
So you have several URLs like `http://1.1.1.1/path`, `http://1.1.1.2/path` and so on, right?

Then I'd suggest creating a new abstraction/function `function getURL(originalURL)` which returns a proxied URL.

**Comment by IonicaBizau** [comment]
@GlauberF I agree with what @ComFreek says. `scrape-it` uses `tinyreq` as a request module. The other way to do it is to fetch the HTML in any way you want, and call `scrapeIt.scrapeHTML(yourHtml, andTheOptionsHere)` (which will return the scraped data), like in #65.

**Comment by GlauberF** [comment]
@ComFreek @IonicaBizau , would have some example to understand better, I'm new to nodejs :)
