### ISSUE TITLE
Add scrapeIt.fromStream function

### ISSUE THREAD

**Issue by ComFreek** [IonicaBizau/scrape-it#83]
What do you think of a `fromStream` function which feeds the HTML parser chunk by chunk instead of allocating one big string in memory?

I have already implemented it and am using it in one of my projects: https://github.com/IonicaBizau/scrape-it/compare/master...ComFreek:master.

I also have a unit test at hand, which requires an upgrade of the package `tester`, as already mentioned at https://github.com/IonicaBizau/tester/issues/15.

```javascript
t.it("scrape from stream", cb => {
    return t.expect(http.get(URL, response => {
        scrapeIt.fromStream(response, {
            title: "h1.title"
          , description: ".description"
          , date: {
                selector: ".date"
              , convert: x => new Date(x)
            }
        })
    })).resolves.toEqual({
        title: "Title"
      , description: "Lorem ipsum"
      , date: new Date("1988-01-01")
    })
})
```

Open points:

- [ ] The normal `scrapeIt` method uses `cheerio-req`, which actually could benefit from the chunk by chunk loading as well.
- [ ] Investigate how htmlparser2 deals with encodings.
- [ ] [from a [later comment](https://github.com/IonicaBizau/scrape-it/issues/83#issuecomment-353850115)] Wait for Cheerio adopting/discussing the `Cheerio.load(dom)` public API: https://github.com/cheeriojs/cheerio/issues/1126

**Comment by IonicaBizau** [comment]
Nice work!

However:

> This function feeds the employed DOM parser chunk by chunk and therefore avoids
fully buffering the HTML in memory.

When passing the `dom` variable to `scrapeHTML`, doesn't that mean it was stored in memory already?

That's what the `tinyreq` does, pretty much: https://github.com/IonicaBizau/tinyreq/blob/a7b01faf2b725953d353a6dc3543279469a4c941/lib/index.js#L87-L92

I'm not sure how this helps, since the HTML will be passed as a variable *anyways*.

**Comment by ComFreek** [comment]
My code only stores the DOM tree in memory, not the HTML string. I think the DOM is necessary for CSS-like selectors in `scrape-it` anyway.*

*) Actually, this exercise seems quite interesting: "Given a set of CSS selectors, does a program exist, which extracts the results from *sequential* HTML parsing?"

**Comment by IonicaBizau** [comment]
> My code only stores the DOM tree in memory, not the HTML string. I think the DOM is necessary for CSS-like selectors in scrape-it anyway.*

That sounds good. But, is that tree compatible with Cheerio? It's still unclear to me if `dom` is in the end stringified again and then processed by cheerio.

**Comment by ComFreek** [comment]
| Description  | Source |
| ------------- | ------------- |
| We call `Cheerio.load(dom)`. | [`Cheerio.load` function](https://github.com/cheeriojs/cheerio/blob/6084a22775788a327e3ec8f632040901b0a0bb9c/lib/static.js#L17) |
| It calls the function `parse(dom, someOptions)`. | [line with call](https://github.com/cheeriojs/cheerio/blob/6084a22775788a327e3ec8f632040901b0a0bb9c/lib/static.js#L22) |
| `parse(content, options)` now calls `evaluate(content, options)`. | [line with call](https://github.com/cheeriojs/cheerio/blob/6084a22775788a327e3ec8f632040901b0a0bb9c/lib/parse.js#L10) |
| `evaluate(content, options)` will just pass through `content`, if a DOM tree has already been provided. | [an *if* condition catching DOM trees](https://github.com/cheeriojs/cheerio/blob/6084a22775788a327e3ec8f632040901b0a0bb9c/lib/parse.js#L30) |

In the course of creating that table myself, I realized that Cheerio indeed adds its `<root>` tag in table line 3. So my warning in the `.fromStream` docblock is wrong and unnecessary.

The only thing to be still wary of is that [`Cheerio.load`'s](https://github.com/cheeriojs/cheerio/blob/6084a22775788a327e3ec8f632040901b0a0bb9c/lib/static.js#L17) public API only states that it accepts a string, not a DOM. I have now created an issue for that: https://github.com/cheeriojs/cheerio/issues/1126

**Comment by IonicaBizau** [comment]
@ComFreek Sounds good! 👍 Should we wait for the stream function to be implemented in Cheerio?

**Comment by ComFreek** [comment]
According to [this comment](https://github.com/cheeriojs/cheerio/issues/1126#issuecomment-353882952), my code should actually use `parse5` instead of old `htmlparser2`, which has apparently only been retained for backwards compatbility in Cheerio.

I think we could adopt a `scrapeIt.fromStream` function (rewritten with `parse5`) and open a PR at Cheerio at the same time. Replace {we} by @ComFreek 

Maybe at this point it should also be considered how `scrapeIt` handles HTML fragments. Should there be a difference in the API call, e.g. `scrapeIt(<URL to full doc>)` and `scrapeIt.fromFragment(<URL to HTML part only>)`? The module `parse5` does draw a line there: https://github.com/inikulin/parse5/issues/227. I am not sure how it would parse HTML neither  `<html>` nor `<body>` in its 'normal' mode.

**Comment by IonicaBizau** [comment]
I am going to close this, but contributions are welcome via PRs! 🚀
