### ISSUE TITLE
Access To Response Object in Promise

### ISSUE THREAD

**Issue by joemccann** [IonicaBizau/scrape-it#90]
I need to check the response code from a scrape.  How can I get access to this via promise api?

It seems to only return the page's data, not the response object?

**Comment by IonicaBizau** [comment]
Currently that's not possible indeed. I'm not sure how we implement it, maybe something like this:

```js
scrape(...).then(({ response, data }) => {
   ...
})
```

Ideas welcome!

**Comment by joemccann** [comment]
Yeah that would be fine!

**Comment by IonicaBizau** [comment]
I'm on it. :rocket:

**Comment by IonicaBizau** [comment]
:ship: **`5.0.0`** :tada:

**Comment by joemccann** [comment]
awesome thanks!
