### ISSUE TITLE
Double Result because of <br>

### ISSUE THREAD

**Issue by jcsrb** [IonicaBizau/scrape-it#91]
Using this domain as example
https://www.apple.com/shop/buy-mac/macbook-pro/13-inch
![image](https://user-images.githubusercontent.com/119011/35484872-6a834eb2-045f-11e8-8448-c45cf2502769.png)

returns the name twice
`"2.3GHz Processor 128GB Storage2.3GHz Processor 128GB Storage"`

see example here
https://runkit.com/jcsrb/5a6e0211354f1f00128a6d55

**Comment by IonicaBizau** [comment]
It's because `as-macbundle-modelvariationtitle` appears twice in the HTML.

Try something like this:

```js
const scrapeIt = require('scrape-it');
const data = await scrapeIt("https://www.apple.com/shop/buy-mac/macbook-pro", {
    products: {
        listItem: ".as-macbundle",
        data: {
            name: ".as-macbundle-modelvariationtitle:first-of-type",
            price: ".as-price-currentprice span"
        }
    }
  });
```

**Comment by jcsrb** [comment]
do I feel silly now :) thanks

**Comment by IonicaBizau** [comment]
No worries, glad it works! :grin:
