### ISSUE TITLE
The TypeScript typings have errors and make this library unusable from TypeScript

### ISSUE THREAD

**Issue by slikts** [IonicaBizau/scrape-it#96]
The TypeScript typings have errors that prevent code depending on this library from compiling in TypeScript; namely, the `CheerioSelector` and `CheerioStatic` types are missing definitions.

I'm not sure what the proper fix is; I made a fork that adds `/// <reference path="../../../@types/cheerio/index.d.ts" />` to `lib/index.d.ts` so that the library would compile, but it seems like a 'hacky' workaround.

**Comment by edorivai** [comment]
For what it's worth, installing `@types/cheerio` let's me compile. Not sure how to define dependencies for `@types`.

**Comment by slikts** [comment]
Seems like it should be a peer dependency.

**Comment by edorivai** [comment]
But isn't that kinda weird, because then non-TS users will get "missing peer dependency" warnings

**Comment by slikts** [comment]
Non-TS users can still benefit from TS typings; for example, VS Code TS type intelligence also works in JS files.

**Comment by edorivai** [comment]
Hmm, good point :thinking:

**Comment by IonicaBizau** [comment]
I merged #101. I'm wondering if this is still an issue. Can you check?

**Comment by edorivai** [comment]
@IonicaBizau If I remember correctly, #101 was not meant to fix _this_ issue. It arose from another change that just contained faulty TS.

**Comment by kpratik2015** [comment]
> The TypeScript typings have errors that prevent code depending on this library from compiling in TypeScript; namely, the `CheerioSelector` and `CheerioStatic` types are missing definitions.
> 
> I'm not sure what the proper fix is; I made a fork that adds `/// <reference path="../../../@types/cheerio/index.d.ts" />` to `lib/index.d.ts` so that the library would compile, but it seems like a 'hacky' workaround.

I had to put `/// <reference path="../../../node_modules/@types/cheerio/index" />`

**Comment by IonicaBizau** [comment]
Is this still a thing? I am not expert in TS, but I merged some related PRs.

**Comment by IonicaBizau** [comment]
Duplicate of #121 

Moving the discussion there.
