### ISSUE TITLE
Call with multiple URLs

### ISSUE THREAD

**Issue by iamtekeste** [IonicaBizau/scrape-it#97]
I would like to start by saying how much I love this package! It's API is so easy to get started with and understand. And this is not an issue really. It is more of me asking for help.

I am trying to scrape a website where the data I am looking for could either be in
`example.com/title` or `example.com/title-year`. I was wondering how I could make `scrape-it` to retry with the second URL if the first one returns a `404` response.

Thanks!

**Comment by edorivai** [comment]
Doesn't sound like the responsibility of this library, in my opinion.

Perhaps you could try this:

```js
scrapeIt('http://example.com/title', { ...your config })
  .catch(() => scrapeIt('http://example.com/title-2018', { ...your config }))
  .then(({ data }) => {
    console.log(data);
  });
```

**Comment by iamtekeste** [comment]
You are 100% correct, this not an issue with the library!
Thanks for the help!
